// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCd4qZ61v0eCX19XGUz3JPOxT5MiufsgE',
    appId: '1:949706656115:web:f74d504e0dc172922edd06',
    messagingSenderId: '949706656115',
    projectId: 'dbpde2100',
    authDomain: 'dbpde2100.firebaseapp.com',
    databaseURL: 'https://dbpde2100-default-rtdb.firebaseio.com',
    storageBucket: 'dbpde2100.appspot.com',
    measurementId: 'G-V2FKXR1RZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLJE9PkrQikvgLvytSs41af5mD9BRPk6I',
    appId: '1:949706656115:android:ce80e4df598787972edd06',
    messagingSenderId: '949706656115',
    projectId: 'dbpde2100',
    databaseURL: 'https://dbpde2100-default-rtdb.firebaseio.com',
    storageBucket: 'dbpde2100.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqIa1vmacZO7x8xlunW_EOxfTp7XJblXQ',
    appId: '1:949706656115:ios:6fa9ea2b8532d33e2edd06',
    messagingSenderId: '949706656115',
    projectId: 'dbpde2100',
    databaseURL: 'https://dbpde2100-default-rtdb.firebaseio.com',
    storageBucket: 'dbpde2100.appspot.com',
    iosClientId: '949706656115-1k8dmom53espgo6cg99kj8n6qvf0cnb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.hispecsPde2101',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqIa1vmacZO7x8xlunW_EOxfTp7XJblXQ',
    appId: '1:949706656115:ios:6fa9ea2b8532d33e2edd06',
    messagingSenderId: '949706656115',
    projectId: 'dbpde2100',
    databaseURL: 'https://dbpde2100-default-rtdb.firebaseio.com',
    storageBucket: 'dbpde2100.appspot.com',
    iosClientId: '949706656115-1k8dmom53espgo6cg99kj8n6qvf0cnb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.hispecsPde2101',
  );
}
